export const QUERY_KEYS = {
  profile: ['profile'],
  skills: ['skills'],
  xpLog: ['xp-log'],
  achievements: ['achievements'],
  lockedContent: ['locked-content'],
  activeCapacity: ['active-capacity'],
  clients: ['clients'],
  reachouts: ['reachouts'],
  treasuryIncome: ['treasury-income'],
  treasuryExpenses: ['treasury-expenses'],
  treasuryLedger: ['treasury-ledger'],
  taskPool: ['task-pool'],
  dailyQuests: ['daily-quests'],
  weeklyQuests: ['weekly-quests'],
  questLog: ['quest-log'],
  rankGateAudit: ['rank-gate-audit'],
  raidSpoils: (clientId) => ['raid-spoils', clientId],
  raidBattles: (clientId) => ['raid-battles', clientId],
}