import {
  TREASURY_LIFETIME_TIERS,
  TREASURY_MONTH_REVENUE_KEYS,
  TREASURY_MONTH_TIERS,
  TREASURY_VAULT_LIFETIME_KEYS,
} from '@/constants/treasuryMilestoneTiers'

export { TREASURY_LIFETIME_TIERS, TREASURY_MONTH_TIERS } from '@/constants/treasuryMilestoneTiers'

export const TREASURY_INFLOW_EVENT_COUNTS = {
  RAIN_5: 5,
  RAIN_25: 25,
  RAIN_50: 50,
  RAIN_100: 100,
}

export const TREASURY_EXPENSE_EVENT_COUNTS = {
  FIRST: 1,
  TRACKER_5: 5,
  TRACKER_25: 25,
}

export const TREASURY_MONTH_HEAVY_EXPENSE_NGN = 200_000
export const TREASURY_MONTH_PROFIT_MIN_NGN = 50_000

export const TREASURY_INFLOW_COUNT_KEYS = [
  'OPEN_ACCOUNT',
  'INVOICE_RAIN_5',
  'INVOICE_RAIN_25',
  'INFLOW_RAIN_50',
  'INFLOW_RAIN_100',
]

export const TREASURY_EXPENSE_KEYS = [
  'LEDGER_FIRST_DEBIT',
  'LEDGER_DEBIT_5',
  'LEDGER_DEBIT_25',
  'TREASURY_HEAVY_MONTH',
  'TREASURY_PROFIT_MONTH',
  'TREASURY_ZERO_OUTSTANDING',
]

export const TREASURY_SESSION_SURPRISE_KEYS = [
  ...TREASURY_INFLOW_COUNT_KEYS,
  ...TREASURY_VAULT_LIFETIME_KEYS,
  ...TREASURY_MONTH_REVENUE_KEYS,
  'TREASURY_ZERO_OUTSTANDING',
]

export const TREASURY_INCOME_EVENT_KEYS = [
  ...TREASURY_INFLOW_COUNT_KEYS,
  ...TREASURY_VAULT_LIFETIME_KEYS,
  ...TREASURY_MONTH_REVENUE_KEYS,
  'TREASURY_ZERO_OUTSTANDING',
]
