export const XP_EVENT_VALUES = {
  HUNT_LAUNCHED: 10,
  HUNT_OUTCOME_SUCCESSFUL: 25,
  HUNT_OUTCOME_REJECTED: 12,
  HUNT_OUTCOME_GHOSTED: 10,
  /** @deprecated use HUNT_LAUNCHED */
  REACHOUT_SENT: 10,
  PROPOSAL_SENT: 25,
  CLIENT_SIGNED: 200,
  REJECTION_RECEIVED: 15,
  INVOICE_PAID: 75,
  RAID_BATTLE: 25,
  RAID_RECURRING_CLAIM: 12,
  RAID_RETREAT: 18,
  RAID_COMPLETE: 200,
  DAILY_QUEST_COMPLETED: 30,
  WEEKLY_QUEST_COMPLETED: 80,
  DAILY_QUEST_FAILED: -20,
  WEEKLY_QUEST_FAILED: -50,
}

export const XP_EVENT_TYPES = {
  HUNT_LAUNCHED: 'hunt_launched',
  HUNT_OUTCOME_SUCCESSFUL: 'hunt_outcome_successful',
  HUNT_OUTCOME_REJECTED: 'hunt_outcome_rejected',
  HUNT_OUTCOME_GHOSTED: 'hunt_outcome_ghosted',
  REACHOUT_SENT: 'reachout_sent',
  PROPOSAL_SENT: 'proposal_sent',
  CLIENT_SIGNED: 'client_signed',
  REJECTION_RECEIVED: 'rejection_received',
  INVOICE_PAID: 'invoice_paid',
  RAID_BATTLE: 'raid_battle',
  RAID_RECURRING_CLAIM: 'raid_recurring_claim',
  RAID_RETREAT: 'raid_retreat',
  RAID_COMPLETE: 'raid_complete',
  DAILY_QUEST_COMPLETED: 'daily_quest_completed',
  WEEKLY_QUEST_COMPLETED: 'weekly_quest_completed',
  DAILY_QUEST_FAILED: 'daily_quest_failed',
  WEEKLY_QUEST_FAILED: 'weekly_quest_failed',
  SYSTEM_QUEST_REJECTED: 'system_quest_rejected',
  TREASURY_EXPENSE_LOGGED: 'treasury_expense_logged',
}
